# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/body_sites', type: :request do
  # BodySite. As you add validations to BodySite, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      BodySite.create! valid_attributes
      get body_sites_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      body_site = BodySite.create! valid_attributes
      get body_site_url(body_site)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_body_site_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      body_site = BodySite.create! valid_attributes
      get edit_body_site_url(body_site)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new BodySite' do
        expect {
          post body_sites_url, params: { body_site: valid_attributes }
        }.to change(BodySite, :count).by(1)
      end

      it 'redirects to the created body_site' do
        post body_sites_url, params: { body_site: valid_attributes }
        expect(response).to redirect_to(body_site_url(BodySite.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new BodySite' do
        expect {
          post body_sites_url, params: { body_site: invalid_attributes }
        }.to change(BodySite, :count).by(0)
      end

      it 'renders a successful response (i.e. to display the "new" template)' do
        post body_sites_url, params: { body_site: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) {
        skip('Add a hash of attributes valid for your model')
      }

      it 'updates the requested body_site' do
        body_site = BodySite.create! valid_attributes
        patch body_site_url(body_site), params: { body_site: new_attributes }
        body_site.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the body_site' do
        body_site = BodySite.create! valid_attributes
        patch body_site_url(body_site), params: { body_site: new_attributes }
        body_site.reload
        expect(response).to redirect_to(body_site_url(body_site))
      end
    end

    context 'with invalid parameters' do
      it 'renders a successful response (i.e. to display the "edit" template)' do
        body_site = BodySite.create! valid_attributes
        patch body_site_url(body_site), params: { body_site: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested body_site' do
      body_site = BodySite.create! valid_attributes
      expect {
        delete body_site_url(body_site)
      }.to change(BodySite, :count).by(-1)
    end

    it 'redirects to the body_sites list' do
      body_site = BodySite.create! valid_attributes
      delete body_site_url(body_site)
      expect(response).to redirect_to(body_sites_url)
    end
  end
end
