---
################################
## WIP: Custom Testing Action ##
################################

name: RSpec

on: [push]

jobs:
  rspec:
    name: Rspec - App
    runs-on: ubuntu-18.04
    container:
      # image: ubuntu:bionic
      image: ruby:2.7.2

    services:
      # Note: this name/label has to be passed to the rails app as the db host
      postgres_service:
        image: postgres:13.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cid_test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: install PostgreSQL client
        run: apt-get update -qq && apt-get install libpq-dev

      - uses: actions/checkout@v2

      - name: Set up Ruby using .ruby-version from repo
        uses: actions/setup-ruby@v1

      - name: Build & test App
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cid_test
          DATABASE_HOST: postgres_service
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rspec spec

